# Generated by Django 2.1.7 on 2020-08-01 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('transaction', '0003_auto_20200801_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagetransaction',
            name='foodgrain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.FoodGrain'),
        ),
    ]
